### ISSUE TITLE
Complete UI

### ISSUE THREAD

**Issue by eysk-io** [416-MemoryLane/issue-tracking#17]
UI: https://www.figma.com/file/ATUeM8tYd5STfa7IFBwFFJ/Untitled?node-id=0%3A1&t=vJQnNq7t65PGKrBY-1

Prototype: https://www.figma.com/proto/ATUeM8tYd5STfa7IFBwFFJ/Untitled?node-id=5%3A234&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=5%3A234

**Comment by scott-m-king** [comment]
DONE
