### ISSUE TITLE
[SPIKE] Authentication and Authorization via a central server

### ISSUE THREAD

**Issue by eysk-io** [416-MemoryLane/issue-tracking#7]
Both authentication and authorization are required for access to albums. This will be managed by Galactus, a centralised deployed service and server in a client-server architecture. This centralisation is required for our application, to ensure that the peer-to-peer network is enforced around album access authorization.

Galactus will keep a record of all albums and the users which have access to these albums. At the same time, for each user it will contain a list of the albums the user has access to. When we have a user that has been granted access to the album, Galactus will perform an atomic operation to a central database that will do the following two things:

- Add the user to this list of albums and their users
- Add the album to the list of albums that the user is part of

A significant challenge for this module (and Wingman) will be accounting for the fact that the IP address of the connection during a session for a node will be likely different every time the node joins a network. As well, if the node is not gracefully shutdown with a process to indicate a stale IP address in the database, another node with access to the same album would try to connect to the stale IP address.

**Comment by scott-m-king** [comment]
SPIKE doc: https://docs.google.com/document/d/1Uxg_q5zpd2nTs63gjDt3Xs7Tj9jFVOY2QxnlpV-8hbA/edit?usp=sharing
